version: "2"
services:
  #  app:
  #    container_name: notepat-app
  #    build:
  #      context: ../
  #      dockerfile: deployments/app/Dockerfile
  #    ports:
  #      - "5000:5000"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="mongouser"
      - MONGODB_PASS="mongopass"
    volumes:
      - mongodb-data:/data/db
        #      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
volumes:
  mongodb-data:
    external:
      name: mongodb-data

